language:
  - swift

os:
  - osx

osx_image:
  - xcode12.2

script:
  - xcodebuild test -project Travis-CI-With-iOS-Project.xcodeproj -scheme Travis-CI-With-iOS-Project -destination "platform=iOS Simulator,name=iPhone 12"
